name: cicd

on:
  # ! remove "branches-ignore" and use "branches" with your chosen branches
  push:
    branches-ignore:
      - '**'
    # branches:
    #   - master
  pull_request:
    branches-ignore:
      - '**'
    # branches:
    #   - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14', '16']

    steps:
      - uses: actions/checkout@v2

      - name: setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.1.8

      - name: setup cache ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm validate

      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/lcov.info

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        with:
          fetch-depth: 0
          token: ${{ secrets.SEMANTIC_RELEASE }}
        uses: actions/checkout@v2

      - name: setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.1.8

      - name: setup cache ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Configure NPM Registry
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - run: pnpm install --frozen-lockfile

      - name: Publish to NPM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
