name: pull_request

on: [pull_request]

jobs:
  code_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14', '16', '18']

    steps:
      - name: 🏗 Setup Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🏗 Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.x

      - name: 🏗 Setup cache ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: 📦 Install
        run: pnpm install --frozen-lockfile

      - name: 🚨 Lint
        run: pnpm lint

      - name: 🎨 Format
        run: pnpm format

      - name: 🏷️ Type Check
        run: pnpm ts

      - name: ✅ Test
        run: pnpm test:coverage

      - name: ✅ Coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/coverage-final.json

      - name: 🔧 Build
        run: pnpm build

  commit_check:
    runs-on: ubuntu-latest

    steps:
      - name: 🏗 Setup Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🚨 Commitlint
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .commitlintrc.yml

  spell_check:
    runs-on: ubuntu-latest

    steps:
      - name: 🏗 Setup Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🚨 Spellcheck
        uses: streetsidesoftware/cspell-action@v2.12.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          inline: error
